### ISSUE TITLE
more time to read, please!

### ISSUE THREAD

**Issue by omarcostahamido** [jacktrip-webrtc/jacktrip-webrtc#7]
Add more time to read the little pop-up window that appears on the top right hand side of the screen.
(even: better a way to display it again!)

O

**Comment by matteosacchetto** [comment]
Regarding the amount of time, shure, more time can be helpful (i've see that on #8 you already did it, great!).  
  
Regarding the "display it again" part, well, the idea of the notification was just to inform the user that once the room has been created he just needs to copy the link and share it with the other parties, and to give him a quick way to copy the link. I'm not shure if being able to display it again could be of any help, since he can always copy the link in the address bar.

**Comment by omarcostahamido** [comment]
then I guess change the place and type of pop-up. It is not immediately clear that is it as simple as that.
Maybe place the pop up in the middle and include an arrow up pointing to the address bar saying something like copy this to invite other people..
just an idea to make more clear.

**Comment by matteosacchetto** [comment]
Yes, that's a great idea. Thanks for the suggestion.
